### ISSUE TITLE
Awards with no text 

### ISSUE THREAD

**Issue by rhudea** [hlxsites/bitdefender#112]
- large image only - seen in https://www.bitdefender.com.au/solutions/vpn.html
![image](https://github.com/hlxsites/bitdefender/assets/1336823/2f6b1677-df56-4b4d-b5ff-d050c3661d88)

- large image with hover effect - seen in https://www.bitdefender.com.au/solutions/digital-identity-protection.html
![image](https://github.com/hlxsites/bitdefender/assets/1336823/3f53a9d0-82de-49e5-8428-ec73205464c1)

**Comment by sergiucoman** [comment]
Maybe a duplicate of https://github.com/hlxsites/bitdefender/issues/27

**Comment by rhudea** [comment]
Duplicate of #27
