### ISSUE TITLE
Device number product cards variations

### ISSUE THREAD

**Issue by lansami** [hlxsites/bitdefender#122]
Create product cards variations for different number of devices and different years plan
Pages with this variation: 
- https://www.bitdefender.com.au/solutions/internet-security.html
- https://www.bitdefender.com.au/solutions/total-security.html
- https://www.bitdefender.com.au/solutions/antivirus.html
- https://www.bitdefender.com.au/solutions/antivirus-for-mac.html
- https://www.bitdefender.com.au/solutions/family-pack.html
- https://www.bitdefender.com.au/solutions/small-office-security.html

![image](https://github.com/hlxsites/bitdefender/assets/26941572/56e3af64-3407-4eab-b5ab-99f0bb0d4fe6)

![image](https://github.com/hlxsites/bitdefender/assets/26941572/32cd4ca6-7e46-4036-bcaa-8b12b612241c)

**Comment by nicolasbarbe** [comment]
All pages listed have been updated with product card variation
