### ISSUE TITLE
Product card variation only for year or month

### ISSUE THREAD

**Issue by lansami** [hlxsites/bitdefender#124]
Create product card variation only for year or month, with the list of included features.
The list can be missing on some other pages https://www.bitdefender.com.au/solutions/digital-identity-protection.html

Found on page https://www.bitdefender.com.au/solutions/vpn.html
![image](https://github.com/hlxsites/bitdefender/assets/26941572/29d07017-6314-4ca5-a581-206eddf1b1ed)

Found on page https://www.bitdefender.com.au/solutions/digital-identity-protection.html
![image](https://github.com/hlxsites/bitdefender/assets/26941572/f710f3e5-765c-4825-afc2-e04b8ecf5284)

**Comment by nsdere** [comment]
**Product Card 2-Cards without any selections** 
**Desktop Issues**: 
- Should be aligned center, 
- old price should have bigger font size
**Mobile Issues**: 
- Green tag(maybe add no padding) and buttons(maybe try padding: 6px 20px) should be thinner, 
- should add Savings 50% banner above the price,  
- should add /mo as an upperscript to the price, 
- link color should be applied for Terms of Use, 
- should remove the dash for 1-month plan, 
- description below the price should be less weighted(500px) and smaller(10px)

**Original vs Franklin(completed implementation)**
<img width="1048" alt="image" src="https://github.com/hlxsites/bitdefender/assets/18396745/37cd9333-dffa-4a70-afba-f2d49b480919">

**Comment by nicolasbarbe** [comment]
https://github.com/hlxsites/bitdefender/pull/289 should address:

- should add Savings 50% banner above the price,
- should add /mo as an upperscript to the price,
