### ISSUE TITLE
Product card variation for accounts including yearly and monthly choices

### ISSUE THREAD

**Issue by lansami** [hlxsites/bitdefender#125]
Created product card variation for one or multiple accounts with the choice of Yearly or Monthly
Some pages may contain a larger list of checkmarks, or a description for multiple devices per year

Found on page https://www.bitdefender.com.au/solutions/password-manager.html
![image](https://github.com/hlxsites/bitdefender/assets/26941572/741a9eaf-23aa-4354-9a0f-f2bf1b5ad864)

Found on page https://www.bitdefender.com.au/solutions/premium-security.html
![image](https://github.com/hlxsites/bitdefender/assets/26941572/85cf06fb-666e-4952-9d5a-8ce7cc331e9d)

**Comment by nsdere** [comment]
**Product Card 2-Cards with yearly-monthly selection** 
**Desktop Issues**: Not aligned center
**Mobile Issues**: Green tag(maybe add no padding) and buttons(maybe try padding: 6px 20px) should be thinner
**Original vs Franklin(incomplete implementation)**
<img width="991" alt="image" src="https://github.com/hlxsites/bitdefender/assets/18396745/03a98a7e-9bb0-44ff-abb8-e65e737f3f0d">
