### ISSUE TITLE
Avoid reload in reader when resizing window

### ISSUE THREAD

**Issue by johan-t** [hlxsites/bitdefender#13]
When crossing the threshold of 1000px width there is a reload in the header to trigger the decorate function to correctly load mobile or desktop header. The reload needs to be removed, while we still need to keep the functionality of loading the correct function when crossing 1000px.

```
const mediaQuery = window.matchMedia('(max-width: 1000px)');
  let lastMatch = mediaQuery.matches;

  function checkMediaQuery() {
    if (mediaQuery.matches !== lastMatch) {
      // eslint-disable-next-line no-restricted-globals
      location.reload();
    }
    lastMatch = mediaQuery.matches;
  }

  mediaQuery.addEventListener('change', checkMediaQuery);

  // Initial rendering based on media query
  if (mediaQuery.matches) {
    renderMobileHeader();
  } else {
    renderDesktopHeader(block);
  }
```

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by johan-t** [comment]
@Pulkitxm I am actually working on it right now in in the Header PR. I just forgot to assign it to myself.
