### ISSUE TITLE
Follow up for awards carousel 

### ISSUE THREAD

**Issue by johan-t** [hlxsites/bitdefender#146]
There are a couple of issues left with the carousel:

1. Animation not working correctly on mobile
2. Use grid instead of Flexbox and move more styles to css instead of JS 

Original: 
https://www.bitdefender.com/solutions/ultimate-security.html

Ours:
https://main--bitdefender--hlxsites.hlx.page/en-au/solutions/ultimate-security

**Comment by sergiucoman** [comment]
The Ultimate security page does not need to be migrated anymore (hence no need to implement this variation of the awards carousel).
