### ISSUE TITLE
Pop-up form implementation

### ISSUE THREAD

**Issue by nsdere** [hlxsites/bitdefender#151]
Have you been exposed? link at the Hero section of Digital Identity Protection page shows a pop up of a form. 

Original Page: https://www.bitdefender.com.au/solutions/digital-identity-protection.html

Screens of the form:
<img width="500" alt="image" src="https://github.com/hlxsites/bitdefender/assets/18396745/ffcc9d4f-acca-4051-8f27-176e7781282e">

<img width="500" alt="Screenshot 2023-08-14 at 13 34 23" src="https://github.com/hlxsites/bitdefender/assets/18396745/4c63b973-08ed-4695-a719-c7afa59dafb0">

<img width="500" alt="Screenshot 2023-08-14 at 12 36 53" src="https://github.com/hlxsites/bitdefender/assets/18396745/314879ca-8bac-4cd4-9102-8ec1d7161edf">

<img width="500" alt="Screenshot 2023-08-14 at 13 34 11" src="https://github.com/hlxsites/bitdefender/assets/18396745/3543c1b5-9cbc-46e2-bf42-abf2544dbc42">

<img width="500" alt="image" src="https://github.com/hlxsites/bitdefender/assets/18396745/fb7eba65-22e1-4969-b79e-e271b111841c">

**Comment by nicolasbarbe** [comment]
There is a bug with the current implementation of modal that might break the rendering when the user rename the file. 

When a modal is created, the filename is added as a class. If the user rename the file, the classname changes but the CSS  still contains the old name.

Here is the part of the code:
```
export async function createModal(path, template) {
  [...]

  // add class to modal container for opportunity to add custom modal styling
  if (template) modalContainer.classList.add(template);
  [...]
}
```
Where the argument `template` is the filename.

I suggest to change the logic to use a Template page metadata if provided, and fallback to the filename if missing.

**Comment by basecode** [comment]
@nicolasbarbe True, we're aware actually :) the template page meta data doesn't work unfortunately if we request the `plain.html` selector. Any other idea is welcomed.
