### ISSUE TITLE
Sidekick Library does not copy separator

### ISSUE THREAD

**Issue by basecode** [hlxsites/bitdefender#159]
In the product cards we use `---` separator. The sidekick ignores the separator and doesn't copy it to clipboard.

https://main--bitdefender--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/products&index=0

**Comment by nicolasbarbe** [comment]
let me check if we can simply get rid of separators

**Comment by basecode** [comment]
Maybe it resolves automatically when we update the sidekick lib in the project?
