### ISSUE TITLE
Push product (commerce pim) data to datalayer

### ISSUE THREAD

**Issue by basecode** [hlxsites/bitdefender#186]

**Comment by astoicescu-bd** [comment]
On pages dedicated to one specific product, data is required into the data layer with the help of a dedicated event:

`window.adobeDataLayer = window.adobeDataLayer || [];
window.adobeDataLayer.push({
	"event": "product loaded",
        "product": [{
		"info": {
		"ID": "<product ID>",
		"name": "<product name>",
		"devices": "<product devices>",
		"subscription": "<product subscription>",
		"version": "<product version>",
		"basePrice": "<product base price>",
		"discountValue": "<product discountValue>",
		"discountRate": "<product discount rate>",
		"currency": "<product currency>",
		"priceWithTax": "<product price with tax>"
		}
	}]
});`

<html>
<body>


Field | Type | Description | Examples
-- | -- | -- | --
product[].info.ID | String | Unique product ID | "8003"
product[].info.name | String | Product name | "Bitdefender Total Security"
product[].info.devices | String | Number of devices on witch the product subscription can be activated. | "5"
product[].info.subscription | String | Product subscription period in months | "12"
product[].info.version | String | Product version | "2020"
product[].info.basePrice | String | Product subscription full price | "59.99"
product[].info.discountValue | String | Product discount value | "29.99"
product[].info.discountRate | String | Product discount percentage | "50"
product[].info.currency | String | Product prices currency | "usd"
product[].info.price | String | Product price payed by the customer without taxesbasePrice-discountValue | "39.99"


</body>
</html>

**Comment by astoicescu-bd** [comment]
This are the product pages:
https://www.bitdefender.com.au/solutions/premium-security.html
https://www.bitdefender.com.au/solutions/total-security.html
https://www.bitdefender.com.au/solutions/family-pack.html
https://www.bitdefender.com.au/solutions/internet-security.html
https://www.bitdefender.com.au/solutions/antivirus.html
https://www.bitdefender.com.au/solutions/antivirus-for-mac.html
https://www.bitdefender.com.au/solutions/mobile-security-ios.html
https://www.bitdefender.com.au/solutions/mobile-security-android.html
https://www.bitdefender.com.au/solutions/vpn.html
https://www.bitdefender.com.au/solutions/password-manager.html
https://www.bitdefender.com.au/solutions/digital-identity-protection.html
