### ISSUE TITLE
Green tags do not work in some cases

### ISSUE THREAD

**Issue by sergiucoman** [hlxsites/bitdefender#189]
The green tags are not properly working for https://main--bitdefender--hlxsites.hlx.page/solutions/mobile-security-android

<img width="424" alt="image" src="https://github.com/hlxsites/bitdefender/assets/22545805/09d13fc1-51b0-44ce-9bdc-4e8242f69510">

@johan-t

**Comment by johan-t** [comment]
The problem was that there was a line break in the content which lead to a change in the HTML that was not recognised by the regex function. Therefore we must remember to not include line-breaks in the tags in the content
