### ISSUE TITLE
Disappearing sticky nav

### ISSUE THREAD

**Issue by sergiucoman** [hlxsites/bitdefender#190]
The navigation menu is displayed initially on the https://main--bitdefender--hlxsites.hlx.page/solutions/mobile-security-android but then it disappears when scrolling down. 

<img width="1302" alt="image" src="https://github.com/hlxsites/bitdefender/assets/22545805/661e9dc1-0124-4af0-9c40-dcc43fd1980e">

**Comment by andreibogdan** [comment]
Fixed. Sticky nav should be on its own section.

![Screenshot 2023-08-18 at 10 32 06](https://github.com/hlxsites/bitdefender/assets/166901/91134dcf-1009-4223-bb62-ce0a993a854f)
