### ISSUE TITLE
Barchart issues

### ISSUE THREAD

**Issue by lansami** [hlxsites/bitdefender#199]
Barchart scores are displayed under the progress bar, should be displayed inline
On https://www.bitdefender.com.au/solutions/
![image](https://github.com/hlxsites/bitdefender/assets/26941572/b546e2f9-869f-4a36-803f-ea1f591ada63)
On https://main--bitdefender--hlxsites.hlx.page/solutions/
![image](https://github.com/hlxsites/bitdefender/assets/26941572/719f6822-2b04-4a8c-be95-cccecc944c9d)

On tablet when two barcharts are displayed, they should be displayed one near another, on the same line
On bitdefender website https://www.bitdefender.com.au/solutions/
![image](https://github.com/hlxsites/bitdefender/assets/26941572/ee1ccf27-fd35-403d-86f9-0fb983dc772f)
On Franklin version https://main--bitdefender--hlxsites.hlx.page/solutions/
![image](https://github.com/hlxsites/bitdefender/assets/26941572/6b4c574e-79e3-4f40-bcbc-271b0b8701c6)
(Checked on a display with width 820px - iPad Air)

Icon displayed on the barchart should be bigger. On bitdefender website the size is `46px or 2.875rem`
On the Franklin version the size is `34px`

`.barchart.block h3` should have a smaller margin of `7px or 04375rem`
font size of the antivirus names is smaller, on bitdefender website is 14px on all devices. I would suggest to make it 14px (`--body-font-size-xs`) on mobile and `--body-font-size-s` on other devices, what do you think?

On mobile there is a space between the icon and the barchart title, seems to be because of the gap used to have a spacing between the icon and the rest of the barchart component. On bitdefender website there is no gap.

**Comment by weird-samuel** [comment]
use grid display style for the bar charts
