### ISSUE TITLE
Product cards - "Save" badge value should not display decimals

### ISSUE THREAD

**Issue by lansami** [hlxsites/bitdefender#224]
Product cards - "Save" badge value should not display decimals

On bitdefender website
![image](https://github.com/hlxsites/bitdefender/assets/26941572/9e82ad48-b974-4796-bdcc-ab81b55205c5)

On franklin version
![image](https://github.com/hlxsites/bitdefender/assets/26941572/466906cf-fb81-4ef4-8a54-ea91adff5b00)

**Comment by nsdere** [comment]
**Product Card 3-Cards with number of devices selections** 
**Desktop Issues**: 
-  The width of the containers should be smaller
- Small office security has no old price, the buttons should be aligned accordingly (has an open ticket: #184)
**Mobile Issues**: 
- decimals should be added to the price value on the "save" badge
- font size of prices should be bigger, 
- link color to terms of use, 
- price should not be bold, 
- thinner button

**Original vs Franklin(completed implementation)**
<img width="859" alt="image" src="https://github.com/hlxsites/bitdefender/assets/18396745/7cca5719-c91b-44d2-ab6d-d669591c1392">
<img width="860" alt="image" src="https://github.com/hlxsites/bitdefender/assets/18396745/43146bc3-2257-4bbc-bd8e-7cf952370a90">
<img width="848" alt="image" src="https://github.com/hlxsites/bitdefender/assets/18396745/2660eb5e-73d2-4df8-89ed-a4fc06f75a94">
