### ISSUE TITLE
Columns with background image needs non black block option

### ISSUE THREAD

**Issue by johan-t** [hlxsites/bitdefender#233]
We need an option to not have a black linear gradient for background images 

Ours:
<img width="1680" alt="Screenshot 2023-08-24 at 15 30 41" src="https://github.com/hlxsites/bitdefender/assets/30388999/82f1a1fc-b26e-42fd-8c46-d9ebd4bb198d">

Original:
<img width="1680" alt="Screenshot 2023-08-24 at 15 31 03" src="https://github.com/hlxsites/bitdefender/assets/30388999/82639b67-d520-471c-a1ec-03a69991d2bd">

**Comment by nsdere** [comment]
Good point. I will try adding this feature on the section metadata as style.
