### ISSUE TITLE
Arrange block to display text over background and other styling

### ISSUE THREAD

**Issue by lansami** [hlxsites/bitdefender#237]
Arrange columns block, maybe add a new variation for the columns, to display the text over the background image like: 
![image](https://github.com/hlxsites/bitdefender/assets/26941572/67b972e0-79e3-4c8e-a620-f0fa9a5d889a)

Other styling
Set the checked mark to css(if posible) - less loading time
arrange column items vertically, on top
add separator only for the section where the lists are displayed
similar to:
![image](https://github.com/hlxsites/bitdefender/assets/26941572/f2b5ee15-cb7c-45d4-8831-4a71d093b266)

Page to check from bitdefender: https://www.bitdefender.com.au/solutions/virus-scanner-for-mac.html
Franklin version: https://main--bitdefender--hlxsites.hlx.page/solutions/virus-scanner-for-mac

**Comment by johan-t** [comment]
Would the text over image be possible with the bg-image section Metadata that @nsdere implemented?

**Comment by lansami** [comment]
We can achieve something similar, but not exactly what we want
![image](https://github.com/hlxsites/bitdefender/assets/26941572/ae7eef81-15ce-44d0-9347-f96a6f360d03)

We would need a variation to be able to set from the column that we want to display a big image with text on the right
