### ISSUE TITLE
Product cards not showing correct values 

### ISSUE THREAD

**Issue by johan-t** [hlxsites/bitdefender#239]
On the page [password-manager ](https://main--bitdefender--hlxsites.hlx.page/solutions/password-manager) the product cards are not showing prices 

<img width="1680" alt="Screenshot 2023-08-25 at 08 19 29" src="https://github.com/hlxsites/bitdefender/assets/30388999/c076932b-d4c1-48c7-9090-ea62b976a975">

**Comment by lansami** [comment]
Issue is related to https://github.com/hlxsites/bitdefender/issues/125

**Comment by sergiucoman** [comment]
This has been fixed by #125
