### ISSUE TITLE
Change hero picture on index

### ISSUE THREAD

**Issue by johan-t** [hlxsites/bitdefender#279]
Ours:
<img width="1679" alt="Screenshot 2023-09-04 at 10 44 02" src="https://github.com/hlxsites/bitdefender/assets/30388999/5b8fe320-34f9-47c6-b309-81d0bc2dd450">

Original:
<img width="1679" alt="Screenshot 2023-09-04 at 10 44 15" src="https://github.com/hlxsites/bitdefender/assets/30388999/eb47c8fb-6d1b-4892-9fa3-7ae0a3150500">

**Comment by basecode** [comment]
We can let the customer do it for training. I moved to post go-live.
