### ISSUE TITLE
Product Cards with 1-Column, no selection

### ISSUE THREAD

**Issue by nsdere** [hlxsites/bitdefender#286]
**Desktop Issues:** product title and price should not be bold for the first year smaller 
**Mobile Issues:** 
- should be no selection, 
- “save” tag should be placed above the price and should not be bold, 
- link color for terms of use, 
- product title(font size: 15px, font-weight:700px) and price(font-weight:400px) should not be bold, 
- green tag and button should be thinner
**Original vs Franklin(Complete implementation)**

<img width="828" alt="image" src="https://github.com/hlxsites/bitdefender/assets/18396745/baace98a-39d9-477b-a3f6-208e74ffdd61">

**Comment by nicolasbarbe** [comment]
https://github.com/hlxsites/bitdefender/pull/289 should fix the first two points (requires content change).

**Comment by johan-t** [comment]
I can fix the remaining styling issues in PR 197
