### ISSUE TITLE
Fix page.attributes in "page load started" event

### ISSUE THREAD

**Issue by basecode** [hlxsites/bitdefender#361]
based on the test URL:
https://main--bitdefender--hlxsites.hlx.live/solutions/?cid=test&icid=test&adobe_mc_ref=test
Event page load started
page.attributes.domain should be helix.live
page.attributes.domainPeriod should be 2
page.info.referringURL is not taking into account the adobe_mc_ref parameter
(URL of the last page that lead to the loading of the current page from document.referrer
If the destinationURL has one of the following query parameters: ref or adobe_mc_ref then the value of the parameter will be used.
So, the referringURL value will be populated in this order:
adobe_mc_ref parameter -> ref parameter  -> document.referrer -> empty)

page.attributes.time is missing the day and time zone, example value: "12:03|12:00-12:59|monday|gmt +2"

**Comment by lansami** [comment]
page.attributes.domain should be `hlx.live`
