### ISSUE TITLE
SOHO should have only a “learn more” button

### ISSUE THREAD

**Issue by andreibogdan** [hlxsites/bitdefender#367]
Steps
Go to https://main--bitdefender--hlxsites.hlx.live/solutions/.
Actual Results
SOHO buy card - wrong redirect for “Learn More” button 
1.1. Privacy solutions - both products Premium VPN and Password Manager - wrong colors for “discover more” buttons
Expected Results
SOHO should have only a “learn more” button, not a buy button, the redirect is wrong, it should redirect the user to [com.au](http://com.au/) PP

![image](https://github.com/hlxsites/bitdefender/assets/166901/0d7fa9c1-6fed-45c7-bf32-d8c19138a4bf)

**Comment by andreibogdan** [comment]
Related to #365

**Comment by basecode** [comment]
Duplicate of https://github.com/hlxsites/bitdefender/issues/365
