### ISSUE TITLE
Premium Security

### ISSUE THREAD

**Issue by andreibogdan** [hlxsites/bitdefender#378]
https://main--bitdefender--hlxsites.hlx.live/solutions/premium-security 

- [x] The button header doesn’t do anything 
- [ ] The buy section is too crowed

**Comment by lansami** [comment]
For the second check, the [PR](https://github.com/hlxsites/bitdefender/pull/381) is closed as duplicate. Issue is fixed in other [PR](https://github.com/hlxsites/bitdefender/pull/384)
