### ISSUE TITLE
Sidekick Library issues

### ISSUE THREAD

**Issue by basecode** [hlxsites/bitdefender#390]
https://main--bitdefender--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks

a few issues

duplicated columns example:

![Screenshot 2023-10-03 at 18 48 04](https://github.com/hlxsites/bitdefender/assets/143527/2cfb4294-e9f2-4105-86ab-afbb8ea3f56d)

modal link not correct

![Screenshot 2023-10-03 at 18 49 20](https://github.com/hlxsites/bitdefender/assets/143527/b13ea0e0-e170-4f87-bdfb-07e489e34c5a)

Unnamed item

![Screenshot 2023-10-03 at 18 50 51](https://github.com/hlxsites/bitdefender/assets/143527/bf8329d4-5721-4d12-b237-a9a0ff31b31d)

Duplicate and unnamed item

![Screenshot 2023-10-03 at 18 51 14](https://github.com/hlxsites/bitdefender/assets/143527/72f03b04-6cc1-453b-af05-3617f8997728)

vpn presentation looks weird. I don't think it's correct :)

![Screenshot 2023-10-03 at 18 51 57](https://github.com/hlxsites/bitdefender/assets/143527/abc943c0-186d-495d-932d-8695f2c628eb)

missing blocks in library:

![Screenshot 2023-10-03 at 18 54 41](https://github.com/hlxsites/bitdefender/assets/143527/c54366bc-4b1a-4a49-b82a-7eeca5709b4b)

vs

![Screenshot 2023-10-03 at 18 55 28](https://github.com/hlxsites/bitdefender/assets/143527/c366a26a-c9eb-4719-807e-c1872f7409d6)

**Comment by sergiucoman** [comment]
Cleaned up the sidekick library. Note that I have removed/unpublished the cards block as it is not used (probably the code should be deprecated as well).
