### ISSUE TITLE
svgs not getting rendered inside blocks

### ISSUE THREAD

**Issue by ext-vradulescu-bf** [hlxsites/bitdefender#395]
Reproducing on: https://main--bitdefender--hlxsites.hlx.page/drafts/vlad/icons

The green svg "new" is not getting rendered on the barchart block in some situations.
In order to fully reproduce this, the page needs to be refreshed several time and observe the bug.

There is a race condition between multiple calls for the **decorateIcons()** method; The **ICONS_CACHE** object value is not getting updated in the right timeline, due to the timing of the async **fetch()** calls ( downloads of the svgs )

![image](https://github.com/hlxsites/bitdefender/assets/140399829/e0ac09fa-7c91-4642-83b2-6230f72aed00)

**Comment by vtsaplin** [comment]
We should review and address the other instances where decorateIcons is reused.
The list can be found here: https://github.com/hlxsites/bitdefender/pull/396#discussion_r1376201705.

**Comment by ext-vradulescu-bf** [comment]
the barchart block was fixed, next follow up issues will be created for other blocks
