### ISSUE TITLE
hreflang parameter

### ISSUE THREAD

**Issue by inastase** [hlxsites/bitdefender#401]
The parameter hreflang needs to be added on all pages

**Comment by andreibogdan** [comment]
@inastase do you want to add hreflang in the header like this example?
![image](https://github.com/hlxsites/bitdefender/assets/166901/f3db02fc-a70d-4c3d-a0f8-ef8e44995d42)

**Comment by inastase** [comment]
yes, the hreflang for au shouldn't have .html at the end of the links
