### ISSUE TITLE
Experiment results not displaying by the Experimentation Pill

### ISSUE THREAD

**Issue by vtsaplin** [hlxsites/bitdefender#436]
Experiment results not displaying: https://main--bitdefender--hlxsites.hlx.page/solutions/

Experimentation framework: https://github.com/adobe/aem-experimentation

**Comment by andreibogdan** [comment]
<img width="683" alt="Screenshot 2024-01-15 at 16 16 29" src="https://github.com/hlxsites/bitdefender/assets/166901/8c11583f-62e7-456a-bc96-040fa4fa5852">
