### ISSUE TITLE
Use rem instead of px for dimensions

### ISSUE THREAD

**Issue by andreibogdan** [hlxsites/bitdefender#55]
**rem** offers a flexible and future-proof way of sizing elements in CSS. It embraces the principles of responsive design, accessibility, and maintainability, making it a preferred choice over px for most web development scenarios.

The **rem** unit is relative to the root element's font size (typically set in the <html> tag). When you set a property using **rem**, it will scale based on the root font size. This means that if you change the root font size, all elements using rem will automatically adjust their sizes proportionally, leading to a consistent layout across different devices and screen sizes. In contrast, **px** is an absolute unit, and setting fixed pixel values may not adapt well to various screen sizes and resolutions.

Unlike **em**, which is relative to the parent element's font size, **rem** units are always relative to the root font size. This consistency makes it simpler to reason about and avoids unexpected cascading effects when dealing with nested elements.

**Comment by basecode** [comment]
Good point! Let's discuss in context of phase 2 scope.
