### ISSUE TITLE
Modal Button in Hero overwritten

### ISSUE THREAD

**Issue by basecode** [hlxsites/bitdefender#60]
![Screenshot 2023-07-28 at 16 00 21](https://github.com/hlxsites/bitdefender/assets/143527/d01b422b-f8ba-4c21-aaff-de63e78b1848)

**Comment by andreibogdan** [comment]
![Screenshot 2023-08-01 at 10 14 31](https://github.com/hlxsites/bitdefender/assets/166901/901f19d2-a272-4076-8ede-a116e4c05e06)
