### ISSUE TITLE
Move  Sticky navigation to its own section

### ISSUE THREAD

**Issue by andreibogdan** [hlxsites/bitdefender#92]
Right now sticky navigation is created under hero section. 
My proposal is to put sticky navigation in separate section like this:
<img width="1012" alt="Screenshot 2023-08-03 at 18 46 26" src="https://github.com/hlxsites/bitdefender/assets/166901/709bb632-7493-4c42-85d0-6468b0e4e8ca">

**Comment by basecode** [comment]
@andreibogdan is this still needed for phase 1? if not, I propose to close.
